name: Cross CI
description: |
  Run cross-ci for rustic* crates
author: "rustic-rs maintainers"
inputs:
  toolchain:
    description: |
      The rust toolchain to use
    required: true
  target:
    description: |
      The target to build for
    required: true
  use-cross:
    description: |
      Use cross to build the binary
    required: true
  os:
    description: |
      The operating system to build for
    required: false
  github-token:
    description: |
      The github token to use
    required: false
  all-features:
    description: |
      Build features with all features
    required: false
    default: "true"
  feature:
    description: |
      The feature to build
    required: false
  project-cache-key:
    default: "rustic"
    description: |
      The project to use, used for caching
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # v1
      with:
        toolchain: ${{ inputs.toolchain }}
        targets: ${{ inputs.target }}

    - name: install compiler
      shell: bash
      if: inputs.target == 'x86_64-unknown-linux-musl'
      run: |
        sudo apt update
        sudo apt-get install -y musl-tools

    - name: Cache brew deps
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      id: brew-cache
      if: inputs.target == 'x86_64-apple-darwin' && inputs.use-cross == 'false'
      with:
        # Paths to cache:
        # /usr/local/Homebrew - installation folder of Homebrew
        # /usr/local/Cellar - installation folder of Homebrew formulae
        # /usr/local/Frameworks, /usr/local/bin, /usr/local/opt - contain (links to) binaries installed by Homebrew formulae
        # /usr/local/lib/python3.9 - Python3 packages installation
        path: |
          /usr/local/Homebrew
          /usr/local/Cellar
          /usr/local/Frameworks
          /usr/local/bin
        key: zld-cache-${{ inputs.target }}

    # FIXME: zld compilation is currently not working
    # - name: install compiler on macos
    #   shell: bash
    #   if: inputs.target == 'x86_64-apple-darwin' && inputs.use-cross == 'false'
    #   run: |
    #     brew install michaeleisel/zld/zld

    - name: install mold linker on linux gnu
      if: inputs.target == 'x86_64-unknown-linux-gnu' && inputs.use-cross == 'false'
      uses: rui314/setup-mold@0bf4f07ef9048ec62a45f9dbf2f098afa49695f0 #v1

    - uses: swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2
      with:
        key: ${{ inputs.target }}
        # A cache key that is used instead of the automatic `job`-based key,
        # and is stable over multiple jobs.
        shared-key: ${{ inputs.project-cache-key }}

    - name: Create .cargo folder if it doesn't exist
      shell: bash
      run: |
        mkdir -p ${GITHUB_WORKSPACE:?}/.cargo

    - name: Use win config
      shell: bash
      if: inputs.target == 'x86_64-pc-windows-msvc'
      run: |
        cp -T ${GITHUB_ACTION_PATH:?}/.config/config-win.toml ${GITHUB_WORKSPACE:?}/.cargo/config.toml

    - name: Use linux config
      shell: bash
      if: inputs.target == 'x86_64-unknown-linux-gnu' && inputs.use-cross == 'false'
      run: |
        cp -T ${GITHUB_ACTION_PATH:?}/.config/config-linux.toml ${GITHUB_WORKSPACE:?}/.cargo/config.toml

    - name: Use darwin config
      shell: bash
      if: inputs.target == 'x86_64-apple-darwin' && inputs.use-cross == 'false'
      run: |
        cp ${GITHUB_ACTION_PATH:?}/.config/config-darwin.toml ${GITHUB_WORKSPACE:?}/.cargo/config.toml

    - name: Cargo check
      uses: clechasseur/rs-cargo@09033b94de93c8dc96e7abb64650169469f553f0 # v2 (attention: this should be double checked for security issues)
      if: inputs.all-features == 'true'
      with:
        command: check
        use-cross: ${{ inputs.use-cross }}
        toolchain: ${{ inputs.toolchain }}
        args: --all-features --target ${{ inputs.target }} --workspace

    - name: Cargo check
      uses: clechasseur/rs-cargo@09033b94de93c8dc96e7abb64650169469f553f0 # v2 (attention: this should be double checked for security issues)
      if: inputs.all-features == 'false'
      with:
        command: check
        use-cross: ${{ inputs.use-cross }}
        toolchain: ${{ inputs.toolchain }}
        args: --features ${{ inputs.feature }} --target ${{ inputs.target }} --workspace
