name: Cross CI
description: |
  Run cross-ci for rustic* crates
author: "rustic-rs maintainers"
inputs:
  toolchain:
    description: |
      The rust toolchain to use
    required: true
  target:
    description: |
      The target to build for
    required: true
  use-cross:
    description: |
      Use cross to build the binary
    required: true
  os:
    description: |
      The operating system to build for
    required: false
  github-token:
    description: |
      The github token to use
    required: false
  all-features:
    description: |
      Build features with all features
    required: false
    default: "true"
  feature:
    description: |
      The feature to build
    required: false
  project-cache-key:
    default: "rustic"
    description: |
      The project to use, used for caching
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248 # v1
      with:
        toolchain: ${{ inputs.toolchain }}
        targets: ${{ inputs.target }}

    - name: install compiler
      shell: bash
      if: inputs.target == 'x86_64-unknown-linux-musl'
      run: |
        sudo apt update
        sudo apt-get install -y musl-tools

    - name: Cache brew deps
      uses: actions/cache@a2ed59d39b352305bdd2f628719a53b2cc4f9613 # v3
      id: brew-cache
      if: inputs.target == 'x86_64-apple-darwin' && inputs.use-cross == 'false'
      with:
        # Paths to cache:
        # /usr/local/Homebrew - installation folder of Homebrew
        # /usr/local/Cellar - installation folder of Homebrew formulae
        # /usr/local/Frameworks, /usr/local/bin, /usr/local/opt - contain (links to) binaries installed by Homebrew formulae
        # /usr/local/lib/python3.9 - Python3 packages installation
        path: |
          /usr/local/Homebrew
          /usr/local/Cellar
          /usr/local/Frameworks
          /usr/local/bin
        key: zld-cache-${{ inputs.target }}

    # FIXME: zld compilation is currently not working
    # - name: install compiler on macos
    #   shell: bash
    #   if: inputs.target == 'x86_64-apple-darwin' && inputs.use-cross == 'false'
    #   run: |
    #     brew install michaeleisel/zld/zld

    - name: install mold linker on linux gnu
      if: inputs.target == 'x86_64-unknown-linux-gnu' && inputs.use-cross == 'false'
      uses: rui314/setup-mold@a06ef6535ccec20261b6f58bbadf24d1ef0e5486 #v1

    - uses: swatinem/rust-cache@378c8285a4eaf12899d11bea686a763e906956af # v2
      with:
        key: ${{ inputs.target }}
        # A cache key that is used instead of the automatic `job`-based key,
        # and is stable over multiple jobs.
        shared-key: ${{ inputs.project-cache-key }}

    - name: Use win config
      shell: bash
      if: inputs.target == 'x86_64-pc-windows-msvc'
      run: |
        cp -T ${GITHUB_ACTION_PATH:?}/.config/config-win.toml ${GITHUB_WORKSPACE:?}/.cargo/config.toml

    - name: Use linux config
      shell: bash
      if: inputs.target == 'x86_64-unknown-linux-gnu' && inputs.use-cross == 'false'
      run: |
        cp -T ${GITHUB_ACTION_PATH:?}/.config/config-linux.toml ${GITHUB_WORKSPACE:?}/.cargo/config.toml

    - name: Use darwin config
      shell: bash
      if: inputs.target == 'x86_64-apple-darwin' && inputs.use-cross == 'false'
      run: |
        cp ${GITHUB_ACTION_PATH:?}/.config/config-darwin.toml ${GITHUB_WORKSPACE:?}/.cargo/config.toml

    - name: Cargo check
      uses: ClementTsang/cargo-action@a211c79cf22973eb590277586fbea20269ca3ca0 # v0 (attention: this should be double checked for security issues)
      if: inputs.all-features == 'true'
      with:
        command: check
        use-cross: ${{ inputs.use-cross }}
        toolchain: ${{ inputs.toolchain }}
        args: --all-features --target ${{ inputs.target }} --workspace

    - name: Cargo check
      uses: ClementTsang/cargo-action@a211c79cf22973eb590277586fbea20269ca3ca0 # v0 (attention: this should be double checked for security issues)
      if: inputs.all-features == 'false'
      with:
        command: check
        use-cross: ${{ inputs.use-cross }}
        toolchain: ${{ inputs.toolchain }}
        args: --features ${{ inputs.feature }} --target ${{ inputs.target }} --workspace
