[build]
rustdocflags = ["--document-private-items"]
# rustflags = "-C target-cpu=native -D warnings"
# incremental = true

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
